feat: adding pre-commit hook and makefile installation script
celestiaorg/celestia-node pull request #1013
Opened 2022-08-17 14:21 UTC by distractedm1nd

2022-08-17 14:24 UTC, adlerjohn reviewed
Pre-commit hooks should generally be avoided IMO.

1. They're not portable.
2. They can lead to issues such as https://github.com/trufflesuite/ganache/issues/562
3. They're unexpected, as they mutate code opaquely.

It's better to _verify_ rather than _execute_, i.e. run `go mod tidy` in CI and fail if there's a diff.

2022-08-17 14:26 UTC, distractedm1nd commented
@adlerjohn Right, but these are not forced, each contributor has to opt-in to it - prevents `chore: lint` commits and yucky `go mod tidy` commits

2022-08-17 14:29 UTC, adlerjohn commented
> each contributor has to opt-in

Do you mean opt-out? The documentation I'm reading says you can opt out with `--no-verify`.

2022-08-17 14:31 UTC, distractedm1nd commented
No, I mean opt-in. You only have to install the hooks if you want. They are not installed automatically when downloading the repo (as with husky), thus adding the command in the makefile. Once you have installed them, you can ignore them for single commits with `--no-verify` if you want (for example, checkpointing during refactorings)

2022-08-17 14:35 UTC, distractedm1nd commented
@adlerjohn https://github.com/celestiaorg/celestia-app/tree/main/contrib/githooks
Celestia app also has them!

2022-08-17 14:37 UTC, adlerjohn commented
Ah got it, thanks.

2022-08-19 14:36 UTC, Wondertan reviewed
Can we also add `make test` in the precommit hook?

2022-08-19 14:36 UTC, Wondertan commented on Makefile
> +init-hooks:
```suggestion
## install: Install git-hooks from .githooks directory.
install-hooks:
```

2022-08-19 14:36 UTC, Wondertan commented on .githooks/pre-commit
> +golangci-lint run
```suggestion
make lint 
```

2022-08-22 06:31 UTC, distractedm1nd commented
@Wondertan Good question, renaynay and I talked about this and decided to leave testing out of the commit hook, because checkpointing/committing shouldn't necessarily mean all tests pass (and, waiting a long time for tests to pass before the commit goes through gets annoying very quickly)

2022-08-22 13:21 UTC, Wondertan approved these changes
Makes sense

2022-08-25 08:55 UTC, vgonkivs commented
I'd suggest:
1) add condition that skips pre-commit hook if go files were not modified(pr with ADRs only)
2) run markdown check in case of 1)

2022-08-25 08:57 UTC, vgonkivs requested changes
I'd suggest:

add condition that skips pre-commit hook if go files were not modified(pr with ADRs only)
run markdown check in case of 1)

2022-08-31 09:16 UTC, Wondertan approved these changes

2022-09-05 00:57 UTC, adlerjohn commented
Relevant: https://github.com/celestiaorg/celestia-app/pull/672

2022-09-05 12:08 UTC, vgonkivs approved these changes

2022-09-05 13:15 UTC, merged