✍️ added Table of Content inside README
celestiaorg/celestia-node pull request #1082
Opened 2022-09-13 08:59 UTC by nitinmewar

2022-09-13 09:12 UTC, renaynay commented
Thank you so much for the contribution @nitinmewar ! 

Is there any way you can split the two commits contained in this PR into separate PRs? One for returning an error with cel-key and the other for updating table of contents?

2022-09-13 09:13 UTC, renaynay requested changes
Thank you!

2022-09-13 09:13 UTC, renaynay commented on cmd/cel-key/node_types.go
> +		return err
```suggestion
		return errors.New("no node type provided")
```

2022-09-13 09:18 UTC, renaynay requested changes

2022-09-13 09:18 UTC, renaynay commented on README.md
> +# Table of Content
```suggestion
# Table of Contents
```

2022-09-13 09:19 UTC, renaynay commented
@nitinmewar if you implement the suggestion on #1081 , we will merge that first and rebase this PR on top once you've implemented the changes requested here.

2022-09-13 10:01 UTC, renaynay commented
@nitinmewar can you rebase this on main?

2022-09-13 10:05 UTC, nitinmewar commented
@renaynay yes sure!!

2022-09-13 10:12 UTC, nitinmewar commented
@renaynay I am trying to rebase my toe branch to main but it is saying branch is up to date. what am I missing?

2022-09-13 11:04 UTC, renaynay commented
git rebase -i upstream/main

make sure this repo is set as upstream

2022-09-13 13:51 UTC, renaynay submitted a review, later dismissed

2022-09-13 13:52 UTC, renaynay reviewed
there is a lint issue @nitinmewar

2022-09-14 10:00 UTC, nitinmewar commented
@renaynay what should I do now?

2022-09-14 10:34 UTC, renaynay commented
from lint error: 
```
README.md:37:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
README.md:38:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
README.md:39:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
README.md:58:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
README.md:59:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
README.md:60:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
README.md:78:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
README.md:79:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
README.md:80:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
Error: Process completed with exit code 1.
```

2022-09-14 10:36 UTC, Wondertan commented
@nitinmewar, try running ` markdownlint --config .markdownlint.yaml '**/*.md' --fix`, if it does not work, you should fix markdown lint errors manually

2022-09-15 11:54 UTC, Wondertan commented
Still failing

2022-09-19 16:51 UTC, Wondertan commented
Yes please @nitinmewar

2022-09-20 10:21 UTC, renaynay approved these changes

2022-09-20 16:42 UTC, Wondertan approved these changes
Thanks, @nitinmewar for starting this and @renaynay, for finishing this

2022-09-20 16:42 UTC, merged