Remove @liamsi from global CODEOWNERS
celestiaorg/celestia-node pull request #1095
Opened 2022-09-14 19:36 UTC by Wondertan

Follows recent discussions and https://github.com/celestiaorg/celestia-core/pull/858

2022-09-15 07:54 UTC, distractedm1nd submitted a review, later dismissed

2022-09-18 12:53 UTC, adlerjohn approved these changes

2022-09-18 13:53 UTC, liamsi requested changes

2022-09-18 13:53 UTC, liamsi commented on .github/CODEOWNERS
> +* @renaynay @Wondertan @vgonkivs @distractedm1nd
Ok, but can you add me and John to the `docs/adr` subdir too?

2022-09-20 11:50 UTC, liamsi approved these changes

2022-09-20 11:51 UTC, liamsi commented on .github/CODEOWNERS
> +* @renaynay @Wondertan @vgonkivs @distractedm1nd
Yes, will review the block sync one now!

2022-09-20 16:29 UTC, renaynay approved these changes
😢

2022-09-20 16:31 UTC, merged