feat(api/rpc): Implement auth middleware on `Server`
celestiaorg/celestia-node pull request #1402
Opened 2022-11-28 07:57 UTC by renaynay

Related to #1187 

**This PR is based on #1313** 

**It implements:** 
* providing a new JWT secret from the `nodebuilder/node` module to both the node module and the rpc server.
* auth middleware for the `rpc.Server` that verifies the given token with the server's secret

In a follow-up PR will come the ability to create an rpc client with elevated permissions (this branch restricts client access to read-only API methods).

2022-12-15 07:53 UTC, renaynay commented on nodebuilder/node/module.go
> +		fx.Provide(func(secret jwt.Signer) Module {
This will be actually used in a later PR (where node module will be able to generate new tokens and verify perms of tokens w the given secret

2022-12-15 10:38 UTC, distractedm1nd requested changes

2022-12-15 10:38 UTC, distractedm1nd commented on api/rpc/permissions/permissions.go
> +	DefaultPerms   = []auth.Permission{"read"}
this is now incorrect, dont forget public

2022-12-15 10:42 UTC, distractedm1nd commented on api/rpc/permissions/permissions.go
> +	DefaultPerms   = []auth.Permission{"read"}
this is why unit tests are failing btw

2022-12-15 13:38 UTC, vgonkivs approved these changes

2022-12-20 08:41 UTC, distractedm1nd approved these changes

2022-12-20 10:31 UTC, Wondertan approved these changes
Glad that jsonrpc does not actually enforce a specific auth dependency. Would also be nice to have some tests here, but I assume they will come in later PRs

2022-12-20 10:31 UTC, Wondertan commented on api/rpc/server.go
> +	"github.com/celestiaorg/celestia-node/api/rpc/permissions"
nit: Name pkg as common`perms`?

2022-12-20 10:32 UTC, walldiss approved these changes

2022-12-20 10:37 UTC, renaynay commented on api/rpc/server.go
> +	"github.com/celestiaorg/celestia-node/api/rpc/permissions"
I will do this in next PR 🙏🏻

2022-12-20 10:49 UTC, merged