fix(header): add extra arg to fix build
celestiaorg/celestia-node pull request #1410
Opened 2022-11-30 18:42 UTC by evan-forbes

## Overview

main isn't building due to a change in the api of a dependency and a recent PR. this PR adds an arbitrary number to fix that. 

NOTE: I don't actually know what number we should put here. 3 seemed like a good number, so I used it.

## Checklist

- [x] New and updated code has appropriate documentation
- [x] New and updated code has new and/or updated testing
- [x] Required CI checks are passing
- [x] Visual proof for any user facing features like CLI or documentation updates
- [x] Linked issues closed with keywords

2022-11-30 18:49 UTC, vgonkivs requested changes
sorry, it's my fault 😢

2022-11-30 18:49 UTC, vgonkivs commented on header/p2p/exchange.go
> +	headers, err := session.getRangeByHeight(ctx, uint64(from.Height)+1, amount, 3)
```suggestion
	headers, err := session.getRangeByHeight(ctx, uint64(from.Height)+1, amount, ex.Params.MaxHeadersPerRequest)
```

2022-11-30 18:55 UTC, vgonkivs approved these changes

2022-12-01 07:25 UTC, renaynay approved these changes

2022-12-01 07:48 UTC, merged