refactor(nodebuilder/p2p): Switch default network from `arabica` to `mocha`
celestiaorg/celestia-node pull request #1462
Opened 2022-12-09 14:26 UTC by renaynay

Based on #1434 

Switches default network from arabica to mocha

2022-12-09 16:16 UTC, Wondertan commented
Oh, what's wrong with the diff?

2022-12-13 16:42 UTC, distractedm1nd requested changes
rebase

2022-12-13 16:43 UTC, distractedm1nd approved these changes

2022-12-13 18:45 UTC, Wondertan approved these changes

2022-12-13 18:46 UTC, merged