fix(node/p2p)!: remove resourse manager and it's API
celestiaorg/celestia-node pull request #1500
Opened 2022-12-16 13:42 UTC by Wondertan

This is a temporary fix for bootstrappers. Infinite Limits seem to be buggy. The proper fix is to update to the latest version of libp2p

2022-12-16 13:57 UTC, vgonkivs approved these changes

2022-12-19 07:59 UTC, renaynay approved these changes

2022-12-19 09:13 UTC, distractedm1nd commented
@Wondertan No we don't need to run openrpc-gen, the error is coming from a missing example type and is unrelated

2022-12-19 09:15 UTC, distractedm1nd requested changes
please update ADR

2022-12-19 09:16 UTC, distractedm1nd approved these changes
Didn't realize not removing from ADR was intentional

2022-12-19 09:26 UTC, merged