share/p2p: move eds sub
celestiaorg/celestia-node pull request #1519
Opened 2022-12-20 12:07 UTC by vgonkivs

## Overview
Self-explanatory

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

2022-12-20 12:33 UTC, distractedm1nd requested changes
shrexpush not sharexpush

2022-12-20 12:47 UTC, renaynay commented on share/p2p/shrexpush/pubsub.go
> +package push
shouldn't this be `shrexpush`

2022-12-20 12:50 UTC, vgonkivs commented on share/p2p/shrexpush/pubsub.go
> +package push
ok

2022-12-20 12:58 UTC, distractedm1nd approved these changes

2022-12-20 13:31 UTC, Wondertan approved these changes
shrexpush we may want to remove share prefixes. Just protocol name is descriptive enough

2022-12-20 13:31 UTC, Wondertan commented on share/p2p/shrexpush/pubsub.go
> +		return nil, fmt.Errorf("share/shrexpush: topic is not started")
nit, but this seems to be enough
```suggestion
		return nil, fmt.Errorf("shrexpush: topic is not started")
```

2022-12-20 13:31 UTC, Wondertan commented on share/p2p/shrexpush/pubsub.go
> +var log = logging.Logger("share/shrexpush")
Nit:
```suggestion
var log = logging.Logger("shrexpush")
```

2022-12-21 09:46 UTC, distractedm1nd approved these changes

2022-12-21 10:23 UTC, renaynay approved these changes

2022-12-21 10:56 UTC, Wondertan approved these changes

2022-12-21 10:59 UTC, merged