bump(metrics): upgrade otel to the latest version
celestiaorg/celestia-node pull request #1537
Opened 2022-12-22 16:41 UTC by vgonkivs

## Overview
**Not ready for review.**
## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

2023-01-27 17:28 UTC, derrandz requested changes
Tested in branch https://github.com/derrandz/celestia-node/tree/bump_otel_v_x_blackbox_metrics which has #1376  against https://github.com/celestiaorg/test-infra/pull/89 and it seems that there is an issue with Histograms in particular.

Not sure if the API has to change as well, can you look into this @vgonkivs pls?

2023-02-01 21:39 UTC, derrandz commented
Tested in branch https://github.com/derrandz/celestia-node/tree/derrandz/test-optl-version-bump-x-bbm which has #1376  against https://github.com/celestiaorg/test-infra/pull/89 and everything is working superb.

Here's a screenshot of the metrics collected (_including uptime metrics_).
(_don't mind the `NO DATA` panels as p2p metrics were purposefully disabled_)

![Screen Shot 2023-02-01 at 22 37 01](https://user-images.githubusercontent.com/13497307/216169325-157e8327-b3d6-4962-8898-a88a56027ec7.png)

2023-02-01 21:39 UTC, derrandz approved these changes
💸 🚢 🧑‍💻

2023-02-02 13:34 UTC, Wondertan approved these changes

2023-02-02 13:35 UTC, distractedm1nd approved these changes

2023-02-02 13:36 UTC, renaynay approved these changes

2023-02-02 14:02 UTC, walldiss approved these changes

2023-02-02 14:25 UTC, merged