fear: add params to syncer
celestiaorg/celestia-node pull request #1544
Opened 2022-12-23 13:14 UTC by vgonkivs

## Overview
Resolves https://github.com/celestiaorg/celestia-node/issues/1543

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

2022-12-23 14:07 UTC, Wondertan commented
Unit test for syncer broke

2023-01-02 07:32 UTC, distractedm1nd requested changes

2023-01-02 07:32 UTC, distractedm1nd commented on header/sync/options.go
> +	// blockTime provides a reference point for the Syncer to determine
```suggestion
	// BlockTime provides a reference point for the Syncer to determine
```

2023-01-02 19:12 UTC, Wondertan commented on header/sync/sync.go
> +	Params *Parameters
So we can unit tests that they are correctly applied in module tests. We have the same for Store tests.

2023-01-03 14:53 UTC, distractedm1nd approved these changes

2023-01-04 09:19 UTC, renaynay approved these changes

2023-01-05 13:49 UTC, Wondertan commented on header/sync/options.go
> +	BlockTime time.Duration
BlockTime is a global network variable and something other than something users should configure independently. Let's keep it private and set it in the nodebuilder from p2p module where it's currently defined

2023-01-05 13:49 UTC, Wondertan commented on header/sync/options.go
> +		return fmt.Errorf("invalid trusted time duration: %v", p.TrustingPeriod)
```suggestion
		return fmt.Errorf("invalid trusting period duration: %v", p.TrustingPeriod)
```

2023-01-05 13:49 UTC, Wondertan commented on header/sync/options.go
> +	BlockTime time.Duration
I see you already set it from modp2p. Let's just privatize this then

2023-01-05 17:27 UTC, Wondertan submitted a review, later dismissed

2023-01-06 09:13 UTC, Wondertan submitted a review, later dismissed

2023-01-06 10:21 UTC, renaynay approved these changes
optional nit (but recommended) is to move `blockTime` to bottom of params struct and document why it's private and why a 0 value is okay.

2023-01-06 10:56 UTC, renaynay approved these changes

2023-01-06 11:01 UTC, Wondertan approved these changes

2023-01-06 11:03 UTC, merged