feat(header/core): Put eds in `eds.Store` in listener
celestiaorg/celestia-node pull request #1562
Opened 2023-01-04 12:09 UTC by renaynay

DRAFT

2023-01-05 14:03 UTC, distractedm1nd requested changes
first pass

2023-01-05 14:03 UTC, distractedm1nd commented on das/daser_test.go
>  	availability_test "github.com/celestiaorg/celestia-node/share/availability/test"
this import should be grouped at bottom (but ik wasnt introduced in this pr)

2023-01-05 14:03 UTC, distractedm1nd commented on header/core/listener.go
> +	storeFn   header.StoreFn
also please add godocs to the fields since these callbacks can be confusing

2023-01-05 15:46 UTC, renaynay commented on header/header.go
> +	eds, err := da.ExtendShares(size, flattened)
bless

2023-01-09 12:55 UTC, renaynay commented
FYI - converted to draft as we should wait on #1304 and then move core listener stuff out of header pkg into core pkg.

2023-01-25 13:51 UTC, renaynay commented
Superseded by #1632

2023-01-25 13:51 UTC, closed without merging