nodebuilder: make proxy constructors private in all modules
celestiaorg/celestia-node pull request #1643
Opened 2023-01-26 12:17 UTC by Jpserrat

## Overview
Closes #1375 
Made all the proxy constructors private except for the Key constructor of the p2p package cause it is also used in swamp

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

2023-01-26 12:22 UTC, Wondertan requested changes
There are many comments with decapitalized names, pls keep them capital

2023-01-26 14:55 UTC, distractedm1nd requested changes
Talked with @Wondertan - the godoc comments were right, the concern was the rest - so I've made suggestions to these to make it easy to apply them

Thank you for this! Your other PR is also in our pipeline :)

2023-01-26 14:55 UTC, distractedm1nd commented on nodebuilder/p2p/bitswap.go
>  // DataExchange provides a constructor for IPFS block's DataExchange over BitSwap.
```suggestion
// dataExchange provides a constructor for IPFS block's DataExchange over BitSwap.
```

2023-01-26 14:55 UTC, distractedm1nd commented on nodebuilder/p2p/host.go
>  // Host returns constructor for Host.
```suggestion
// host returns constructor for Host.
```

2023-01-26 14:55 UTC, distractedm1nd commented on nodebuilder/p2p/ipld.go
>  // BlockService constructs IPFS's BlockService for fetching arbitrary Merkle structures.
```suggestion
// blockService constructs IPFS's BlockService for fetching arbitrary Merkle structures.
```

2023-01-26 14:55 UTC, distractedm1nd commented on nodebuilder/p2p/misc.go
>  // ConnManagerConfig configures connection manager.
```suggestion
// connManagerConfig configures connection manager.
```

2023-01-26 14:55 UTC, distractedm1nd commented on nodebuilder/p2p/misc.go
>  // DefaultConnManagerConfig returns defaults for ConnManagerConfig.
```suggestion
// defaultConnManagerConfig returns defaults for ConnManagerConfig.
```

2023-01-26 14:55 UTC, distractedm1nd commented on nodebuilder/p2p/misc.go
>  // ConnectionManager provides a constructor for ConnectionManager.
```suggestion
// connectionManager provides a constructor for ConnectionManager.
```

2023-01-26 14:55 UTC, distractedm1nd commented on nodebuilder/p2p/misc.go
>  // ConnectionGater constructs a BasicConnectionGater.
```suggestion
// connectionGater constructs a BasicConnectionGater.
```

2023-01-26 14:55 UTC, distractedm1nd commented on nodebuilder/p2p/misc.go
>  // PeerStore constructs a PeerStore.
```suggestion
// peerStore constructs a PeerStore.
```

2023-01-26 14:55 UTC, distractedm1nd commented on nodebuilder/p2p/pubsub.go
>  // PubSub provides a constructor for PubSub protocol with GossipSub routing.
```suggestion
// pubSub provides a constructor for PubSub protocol with GossipSub routing.
```

2023-01-26 14:55 UTC, distractedm1nd commented on nodebuilder/p2p/routing.go
>  // ContentRouting constructs nil content routing,
```suggestion
// contentRouting constructs nil content routing,
```

2023-01-26 14:55 UTC, distractedm1nd commented on nodebuilder/p2p/routing.go
>  // PeerRouting provides constructor for PeerRouting over DHT.
```suggestion
// peerRouting provides constructor for PeerRouting over DHT.
```

2023-01-26 14:55 UTC, distractedm1nd commented on nodebuilder/rpc/constructors.go
>  // RegisterEndpoints registers the given services on the rpc.
```suggestion
// registerEndpoints registers the given services on the rpc.
```

2023-01-26 14:55 UTC, distractedm1nd commented on nodebuilder/state/core.go
>  // CoreAccessor constructs a new instance of state.Module over
```suggestion
// coreAccessor constructs a new instance of state.Module over
```

2023-01-26 19:41 UTC, distractedm1nd approved these changes

2023-01-27 14:00 UTC, Wondertan approved these changes
LGTM

2023-01-30 08:46 UTC, distractedm1nd approved these changes

2023-01-30 10:00 UTC, merged