swamp: rename Components to Config
celestiaorg/celestia-node pull request #1787
Opened 2023-02-20 16:44 UTC by richardgreg

Fixes: #1234

## Overview

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

2023-02-20 17:34 UTC, Wondertan approved these changes
Nice. Thank you

2023-02-20 17:34 UTC, Wondertan requested changes

2023-02-20 17:34 UTC, Wondertan commented on nodebuilder/tests/swamp/config.go
> +func DefaultComponents() *Config {
Wait, this also should be renamed

2023-02-21 08:54 UTC, richardgreg commented on nodebuilder/tests/swamp/config.go
> +func DefaultComponents() *Config {
Done

2023-02-21 09:18 UTC, Wondertan approved these changes

2023-02-21 13:48 UTC, vgonkivs approved these changes

2023-02-21 13:51 UTC, renaynay approved these changes

2023-02-21 13:58 UTC, walldiss approved these changes

2023-02-21 15:44 UTC, merged