feat: Make IP Colocation configurable for pubsub parameters
celestiaorg/celestia-node pull request #1849
Opened 2023-03-01 10:15 UTC by derrandz

## Overview

Closes #1842 

## Checklist

- [x] New and updated code has appropriate documentation
- [x] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [x] Visual proof for any user facing features like CLI or documentation updates
- [x] Linked issues closed with keywords

2023-03-01 10:21 UTC, Wondertan requested changes

2023-03-01 10:21 UTC, Wondertan commented on nodebuilder/p2p/pubsub.go
> +	}
Some simplifications:
* No need to check for an empty slice before iterating, as the range is noop in such cases
* No nee to explicitly set nil when using var
```suggestion
	var ipColocFactWl []*net.IPNet
	for _, strIp := range cfg.IPColocationFactorWhitelist {
		_, ipNet, err := net.ParseCIDR(strIp)
		if err != nil {
			panic(err)
		}
		ipColocFactWl = append(ipColocFactWl, ipNet)
	}
```

2023-03-01 10:21 UTC, Wondertan commented on nodebuilder/p2p/pubsub.go
> +				panic(err)
We should not panic but return a nice error to the user, as it's clearly a misconfiguration by the user

2023-03-01 11:19 UTC, Wondertan approved these changes

2023-03-01 11:19 UTC, Wondertan commented on nodebuilder/p2p/pubsub.go
> +	}
Can we preallocate the number net.IPNet?

2023-03-01 11:25 UTC, Wondertan commented on nodebuilder/p2p/pubsub.go
> +	}
Ah, yes, linter also complains about it

2023-03-01 11:25 UTC, Wondertan commented
Please also make the name feat(modp2p) and set the labels

2023-03-01 12:43 UTC, Wondertan requested changes

2023-03-01 12:43 UTC, Wondertan commented on nodebuilder/p2p/config.go
> +	IPColocationFactorWhitelist []string
```suggestion
	// Allowlist for IPColocation PubSub parameter, a list of string CIDRs
	IPColocationWhitelist []string
```

2023-03-01 12:43 UTC, Wondertan commented on nodebuilder/p2p/pubsub.go
> +			return nil, fmt.Errorf("error while parsing string ip: %+v", err)
```suggestion
			return nil, fmt.Errorf("error while parsing whitelist collocation CIDR string: %w", err)
```

2023-03-01 12:43 UTC, Wondertan commented on nodebuilder/p2p/pubsub.go
> +	var ipColocFactWl []*net.IPNet //nolint
Why not preallocate?

2023-03-01 13:14 UTC, Wondertan requested changes

2023-03-01 13:14 UTC, Wondertan commented on nodebuilder/p2p/pubsub.go
> +	for _, strIP := range cfg.IPColocationFactorWhitelist {
Applying rename suggestion over GH does not change it where it's used so this broken now

2023-03-01 13:22 UTC, Wondertan requested changes

2023-03-01 13:22 UTC, Wondertan commented on nodebuilder/p2p/pubsub.go
> +	ipColocFactWl := make([]*net.IPNet, 0)
It's not a finished preallocation
```suggestion
	ipColocFactWl := make([]*net.IPNet, 0, len(cfg.IPColocationWhitelist))
```

2023-03-01 14:52 UTC, Wondertan commented
> Please also make the name feat(modp2p) and set the labels

2023-03-01 14:54 UTC, derrandz commented
Sorry didn't see that comment, thanks! @Wondertan

2023-03-01 15:00 UTC, Wondertan commented
@derrandz, all our PRs have to have a `kind:` label, as there is CI rule check for this, which you can see it's broken

2023-03-01 15:34 UTC, Wondertan approved these changes

2023-03-02 10:02 UTC, renaynay approved these changes

2023-03-02 10:17 UTC, merged