feat(nodebuilder/node | api): Version the API
celestiaorg/celestia-node pull request #1901
Opened 2023-03-13 19:32 UTC by renaynay

Introduce a version string to the API

2023-03-13 19:33 UTC, renaynay commented
Kinda hesitant to merge this til we have `header.Subscription` endpoint - but who knows how long gomock will take to impl support for generics.

2023-03-17 09:15 UTC, distractedm1nd requested changes
Please check `api/docgen/openrpc.go` line 23 - there is a const there that declares the api version, so we should combine these

2023-03-17 09:41 UTC, renaynay commented
Marking ready for review as API is not yet stable so let's just make it first minor version.

2023-03-17 12:05 UTC, distractedm1nd approved these changes

2023-03-23 09:49 UTC, distractedm1nd approved these changes

2023-03-23 09:49 UTC, Wondertan approved these changes

2023-03-23 09:50 UTC, vgonkivs approved these changes

2023-03-23 10:07 UTC, merged