fix(nodebuilder/header): Cancel subscription when done
celestiaorg/celestia-node pull request #2134
Opened 2023-04-26 15:47 UTC by renaynay

Found while debugging swamp.

We never cancel subscription so when node attempts to shut down, there are outstanding subs that need to be closed.

2023-04-26 15:49 UTC, Wondertan approved these changes

2023-04-26 15:49 UTC, Wondertan commented
🤠

2023-04-26 15:53 UTC, vgonkivs submitted a review, later dismissed
🤠

2023-04-26 16:13 UTC, vgonkivs approved these changes

2023-04-26 16:22 UTC, Wondertan requested changes
Re file name. That's API test, not an rpc tesy

2023-04-26 16:57 UTC, vgonkivs commented on nodebuilder/tests/rpc_test.go
> +		<-sub
🚔

2023-04-27 06:27 UTC, distractedm1nd commented on nodebuilder/tests/rpc_test.go
> +		<-sub
Wait why? Interesting, didnt know this

2023-04-27 06:27 UTC, distractedm1nd approved these changes

2023-04-27 08:09 UTC, Wondertan commented on nodebuilder/tests/rpc_test.go
> +		<-sub
It may if sub is not giving us anything

2023-04-27 13:10 UTC, renaynay commented on nodebuilder/tests/rpc_test.go
> +		<-sub
very tru

2023-04-27 13:21 UTC, Wondertan approved these changes

2023-04-27 13:45 UTC, distractedm1nd approved these changes
yoloACK

2023-04-27 14:40 UTC, merged