fix(header): temporary disable skipping verification
celestiaorg/celestia-node pull request #2449
Opened 2023-07-10 16:26 UTC by Wondertan

This PR disables skipping verification and accepts all the incoming non-adjacent headers. These headers will later be verified via adjacent verification and rejected if invalid. 

Test that proves that Syncer rejects and continues to work with a fault header: https://github.com/celestiaorg/go-header/pull/76

Additionally, the PR reverts the genesis hash change to the hash pointing to height 1.

Supersedes #2443

2023-07-10 16:27 UTC, Wondertan commented
TODO:
- [ ] Issue on the next steps
- [ ] Test sync on mocha

2023-07-10 17:16 UTC, renaynay approved these changes

2023-07-10 17:16 UTC, renaynay commented
check units

2023-07-10 17:16 UTC, renaynay requested changes
likely needs to check verify tests - this breaks one case

2023-07-11 08:01 UTC, vgonkivs approved these changes

2023-07-11 12:55 UTC, Wondertan commented
Closing as this PR is stuck. New one here: https://github.com/celestiaorg/celestia-node/pull/2456

2023-07-11 12:55 UTC, closed without merging