chore(api | nodebuilder)!: Elevate all api permissions to `read` and disallow `public`, remove `client.NewPublicClient`
celestiaorg/celestia-node pull request #2771
Opened 2023-09-27 12:50 UTC by renaynay

We made a decision synchronously with @adlerjohn and @ramin to require at least `read`-level permissions to be able to access *any* endpoint on the node's API. 

Therefore, `NewPublicClient` is no longer necessary.

2023-09-27 12:56 UTC, Wondertan approved these changes

2023-09-27 13:17 UTC, ramin approved these changes

2023-09-28 07:40 UTC, distractedm1nd commented
This is breaking API so needs to either go into feature branch or you bump api version and regenerate the doc

2023-09-28 07:42 UTC, distractedm1nd requested changes
see last comment

2023-10-04 12:16 UTC, distractedm1nd approved these changes

2023-10-04 12:20 UTC, merged