Metrics bridge
celestiaorg/celestia-node pull request #2863
Opened 2023-10-19 15:00 UTC by renaynay

2023-10-26 09:13 UTC, Wondertan commented on core/metrics.go
> +			metric.WithAttributes(attribute.String(subscriptionStuckTimestampKey, time.Now().String())),
Cardinality

2023-10-26 09:13 UTC, Wondertan commented on core/metrics.go
> +		"core_listener_block_time",
add _hist

2023-10-26 14:18 UTC, renaynay commented on core/metrics.go
> +}
can make a good first issue

2023-10-26 14:40 UTC, Wondertan requested changes
I realized that we don't need blockTime metric. The bridge node publishes headers through Subscriber, which goes through that validator, and time is tracked on it. So effectively we will get the same data twice

2023-10-27 09:31 UTC, renaynay commented
@Wondertan the reason i wanted to capture block time here is that it's the only way to know on the DA-side what the approximate block time is so that we can see if there's a difference between core network block time and DA header propagation time. 

I removed it in this commit https://github.com/celestiaorg/celestia-node/pull/2863/commits/403bc9a924410d5675c652e16017cca5b049efc3

2023-10-27 10:40 UTC, Wondertan commented
I understand and it turns out we designed things in a way that we don't need to duplicate anything 😺

2023-10-27 10:56 UTC, Wondertan commented
We should aim to include fetcher metrics here as well

2023-10-30 13:36 UTC, Wondertan commented
Linter btw

2023-11-08 07:38 UTC, Wondertan approved these changes
LGTM

2023-11-14 07:48 UTC, distractedm1nd approved these changes

2023-11-14 11:58 UTC, vgonkivs approved these changes

2023-11-14 14:46 UTC, ramin approved these changes

2023-11-20 10:09 UTC, merged