chore(utils): test sanitizing empty addr
celestiaorg/celestia-node pull request #2998
Opened 2023-12-11 07:02 UTC by estensen

Add coverage to the non-happy path

2023-12-11 09:56 UTC, ramin requested changes
this is cool, lets go a step further, and create a named var in the address.go file (`ErrInvalidIP` maybe) then instead of the expErr being a bool, we can make it an error and give it nil or the expected error and test `require.EqualErorr` or similar as part of the test, then we can skip the !tt.expErr and just test that its nil or the `ErrInvalidIP`

2023-12-11 09:56 UTC, ramin commented on libs/utils/address_test.go
> +		expErr bool
lets just name this `err`

2023-12-14 07:23 UTC, estensen commented on libs/utils/address_test.go
> +			}
Wanted this
```go
require.Equal(t, tt.want, got)
require.ErrorIs(t, tt.err, err)
```

But couldn't get it to work
```go
Error:      	Target error should be in err chain:
            	            	expected: "invalid IP address or hostname given: "
            	            	in chain: "invalid IP address or hostname given"
            	Test:       	TestSanitizeAddr/#00
```

2023-12-21 10:15 UTC, ramin approved these changes
lgtm :shipit:

2023-12-21 12:37 UTC, ramin commented on libs/utils/address_test.go
> +			}
@renaynay created a replacement with the change here to speed us along https://github.com/celestiaorg/celestia-node/pull/3051

2024-01-08 14:01 UTC, closed without merging