chore(utils): test exists function
celestiaorg/celestia-node pull request #3007
Opened 2023-12-14 07:37 UTC by estensen

2023-12-18 11:47 UTC, ramin requested changes

2023-12-18 11:47 UTC, ramin commented on libs/utils/fs_test.go
> +	tmpFile, err := os.CreateTemp("", "test")
i think i'd prefer if we use t.TempDir() here please https://pkg.go.dev/testing#T.TempDir

2023-12-21 10:18 UTC, ramin approved these changes

2023-12-21 12:22 UTC, closed without merging

2024-01-11 09:31 UTC, estensen commented
@ramin why was it approved and then closed?