feat(nodebuilder/blob/cmd): Allow submit multiple blobs through file input
celestiaorg/celestia-node pull request #3008
Opened 2023-12-14 13:23 UTC by sontrinh16

## Description

Closed: #2552 

## Testing:
testing with `mocha` testnet and get the following result:

![Screenshot 2023-12-14 at 14 55 00](https://github.com/celestiaorg/celestia-node/assets/48055119/87597f15-8982-4ce1-b2e7-b1146d88389d)

where `test.json` file contain:
`{
			"Blobs": [
				{
					"namespace": "0x00010203040506070809",
					"blobData": "0x676d"
				},
				{
					"namespace": "0x42690c204d39600fddd3",
					"blobData": "0x676d"
				}
			]
		}`

2023-12-15 14:47 UTC, Wondertan commented
@vgonkivs, please take a look

2024-01-09 12:02 UTC, vgonkivs requested changes
Thanks for your PR @sontrinh16. Left some comments

2024-01-09 14:47 UTC, vgonkivs reviewed
Left some nits but other than that great work 🚀 . Thank you. 

PS. tested locally. Works for me
![Снимок экрана 2024-01-09 в 16 45 20](https://github.com/celestiaorg/celestia-node/assets/40579846/4f24e7ad-54aa-45b9-96bd-c61e82c75795)

2024-01-09 14:47 UTC, vgonkivs commented on nodebuilder/blob/cmd/blob.go
> +	// FlagFileInput allows the user to provide file path to the json file
```suggestion
	// flagFileInput allows the user to provide file path to the json file
```

2024-01-09 14:47 UTC, vgonkivs commented on nodebuilder/blob/cmd/blob.go
> +			return errors.New("PayForBlobs requires two arguments: namespace and blobData")
```suggestion
			return errors.New("submit requires two arguments: namespace and blobData")
```

2024-01-09 14:47 UTC, vgonkivs commented on nodebuilder/blob/cmd/blob.go
> +		var conmmitments []blob.Commitment
typo

2024-01-09 15:08 UTC, sontrinh16 commented on nodebuilder/blob/cmd/blob.go
> +	// FlagFileInput allows the user to provide file path to the json file
yikes miss this one

2024-01-09 22:38 UTC, jcstein commented
testing on mocha-4 testnet using 2 identical blobs

test.json
```json
{ "Blobs": [ { "namespace": "0x0000000000004a6f7368", "blobData": "0x676d" }, { "namespace": "0x0000000000004a6f7368", "blobData": "0x676d" } ] }
```

```bash
$ celestia blob submit --input-file test.json --node.store $NODE_STORE
{
  "result": {
    "height": 910885,
    "commitments": [
      "uYcW7vh+XB1VCbWSjTQJFA3PV89/089LyhaNQ5hXxjY=",
      "uYcW7vh+XB1VCbWSjTQJFA3PV89/089LyhaNQ5hXxjY="
    ]
  }
}
```

2024-01-11 10:29 UTC, distractedm1nd submitted a review, later dismissed
utACK

2024-01-11 11:17 UTC, renaynay submitted a review, later dismissed
utack

2024-01-11 11:30 UTC, vgonkivs approved these changes

2024-01-11 11:32 UTC, ramin approved these changes

2024-01-16 14:57 UTC, ramin commented
@sontrinh16 can you rebase main back onto this please? Then it'll be ready to merge

2024-01-23 10:53 UTC, ramin commented
@sontrinh16 can you rebase main one more time, or if you toggle the "let admin make changes to PR" we can do this and get it merged, thanks

2024-01-25 03:12 UTC, sontrinh16 commented
> @sontrinh16 can you rebase main one more time, or if you toggle the "let admin make changes to PR" we can do this and get it merged, thanks

hmmm i can't find where to toggle but i can add you guys as collaborators

2024-02-13 16:57 UTC, walldiss approved these changes
Thank you for contribution! Looks good 👍

2024-02-13 17:01 UTC, jcstein commented
I have not tested this on the current version of the PR, just at https://github.com/celestiaorg/celestia-node/pull/3008/commits/7587f80696b063902c84e52875efb66492d8c8d0

2024-02-14 07:16 UTC, sontrinh16 commented
i have tested with the newest commit 

![image](https://github.com/celestiaorg/celestia-node/assets/48055119/214f0949-c61a-42d2-af8f-5ce1ec2e4747)

2024-02-14 09:40 UTC, merged