ci(triggers): change release process from tag push to release publish
celestiaorg/celestia-node pull request #3227
Opened 2024-03-01 17:17 UTC by ramin

Updates the CI workflow trigger to run specifically from a release publish, vs pushing a tag. This will separate any testing we do with with any pre-release or temporary tags from triggering the GitHub workflow to generate a release. Instead, only the release published event should trigger this.

2024-03-01 19:34 UTC, Wondertan submitted a review, later dismissed

2024-03-04 10:20 UTC, walldiss submitted a review, later dismissed

2024-03-05 15:14 UTC, MSevey requested changes
minor clean up of the if condition.

2024-03-06 13:32 UTC, walldiss approved these changes

2024-03-06 17:47 UTC, Wondertan approved these changes

2024-03-08 10:09 UTC, merged