WIP: Shwap types refactoring
celestiaorg/celestia-node pull request #3313
Opened 2024-04-16 16:54 UTC by walldiss

Draft of shwap types extractions and refactoring

2024-05-07 21:15 UTC, Wondertan requested changes
General comments:
* Current shwap directory should become a place for bitswap composition and named as so `bitswap`
	* Considering that `shrex` is also technically a composition, we can move the directory under the `p2p` pkg to live along `shrex`. So `shrex` and `bitswap` are together.
	* shwap.pb files should also be renamed
	* Subseqeuently, `shwap/getter` should  be moved to `getters` pkg, until we further improvements in the pkg. Wonder if that causes any dep cycles tho
* IDs should move out of shwap directory into the `share` pkg.
	* They are going to be reused across compositions
	* It doesn't mean IDs should get into the Getter interface yet
		* We can revisit this in a later refactoring
	* Would be awesome to migrate shrex over IDs within shwap work, but doesn't have to be in this PR.

2024-05-07 21:15 UTC, Wondertan commented on share/namespace_test.go
>  			wantErr: false,
Rename relic

2024-05-07 21:15 UTC, Wondertan commented on share/namespace.go
> +// If it is less than 10 bytes, it will be Left padded to size 10 with 0s.
another one

2024-05-07 21:15 UTC, Wondertan commented on share/store/file/file.go
>  	AxisHalf(ctx context.Context, axisType rsmt2d.Axis, axisIdx int) (AxisHalf, error)
random idea to alias rstm2d.Axis to a type defined in share pkg, but def optional

2024-05-07 21:26 UTC, walldiss commented on share/shares.go
> +type Shares []Share
It will remove ability to use same verification code for Cols

2024-05-07 21:27 UTC, walldiss commented on share/share.go
> +func ShareFromProto(s *types_pb.Share) Share {
func (s *Sample) ToProto() *types_pb.Sample

2024-05-07 21:28 UTC, walldiss commented on share/share.go
> +func ShareFromProto(s *types_pb.Share) Share {
nvm. I'll add

2024-05-07 22:11 UTC, abstraking commented on share/shares.go
> +type Shares []Share
We can always extend to Row to Axis

2024-05-07 22:12 UTC, abstraking commented on share/share.go
> +func ShareFromProto(s *types_pb.Share) Share {
Ah, right

2024-05-22 09:50 UTC, walldiss commented
This was preview PR, that was not meant to be merged

2024-05-22 09:50 UTC, closed without merging