Update Docker entrypoint.sh to use new `store.path` flag name
celestiaorg/celestia-node pull request #337
Opened 2022-01-10 18:01 UTC by jbowen93

2022-01-10 18:22 UTC, renaynay submitted a review, later dismissed

2022-01-10 22:25 UTC, adlerjohn commented on CHANGELOG-PENDING.md
> +- [docker] Update entrypoint.sh to reflect new `store.path` flag name
This doesn't match the PR name, also doesn't include the author

2022-01-12 10:18 UTC, renaynay approved these changes

2022-01-12 10:56 UTC, Wondertan requested changes
Would be good if your changelog entry also included a link to the PR, pls

2022-01-18 20:13 UTC, jbowen93 commented
> Would be good if your changelog entry also included a link to the PR, pls

Resolved

2022-01-20 10:46 UTC, renaynay approved these changes

2022-01-21 11:17 UTC, Wondertan approved these changes

2022-01-21 12:23 UTC, merged