fix: 3575
celestiaorg/celestia-node pull request #3580
Opened 2024-07-19 12:25 UTC by sebasti810

fixes #3575

2024-07-19 13:39 UTC, jcstein commented
does this time out the transaction in the mempool, or just in the client?

2024-07-19 14:02 UTC, sebasti810 commented
just in the client. is it supposed to also set it for the mempool?

2024-07-19 14:08 UTC, jcstein commented
I'm thinking of a case where I send transaction with nonce x, it times out, and then when I go to send another transaction, also with nonce x, it errors because it has the same nonce as the tx that is already timed out on client, but in the mempool

2024-07-19 14:09 UTC, vgonkivs commented
But node does not support nonce so far. We agreed that's it is not necessary.

2024-07-19 14:14 UTC, distractedm1nd commented
> I'm thinking of a case where I send transaction with nonce x, it times out, and then when I go to send another transaction, also with nonce x, it errors because it has the same nonce as the tx that is already timed out on client, but in the mempool

This does not happen anymore - the nonce error was fixed by upgrading app :)

> But node does not support nonce so far. We agreed that's it is not necessary.

I don't think he's saying we need to support nonce, I think @jcstein was just describing that what happens with a nonce in the background was throwing errors to the user, and that a timeout for txs in the mempool could fix this. 

What if we add a timeout to `TxConfig` in a separate issue?

2024-07-19 14:16 UTC, vgonkivs commented
I'd rather pass it through the context.

2024-07-19 14:17 UTC, distractedm1nd commented
Fair, I guess we can't have a timeout in the transaction itself that gets submitted, right?

2024-07-19 14:17 UTC, vgonkivs commented
I don't want to grow the TxConfig. Timeout is smth we can configure through the context.
wdyt @distractedm1nd ?

2024-07-19 16:39 UTC, jcstein commented
> This does not happen anymore - the nonce error was fixed by upgrading app :)
😄 🚢

2024-08-13 10:18 UTC, renaynay commented
@jcstein Did you test this PR already?

2024-08-13 12:05 UTC, renaynay approved these changes

2024-08-13 12:20 UTC, cristaloleg approved these changes

2024-08-13 14:43 UTC, walldiss approved these changes

2024-08-14 09:58 UTC, vgonkivs commented on cmd/rpc.go
> +		"Timeout for RPC requests (e.g. 30s, 1m)",
Could you describe how the user should interact with the flag? In what units the timeout should be passed, bc duration represents time in nanoseconds.?

2024-08-14 09:59 UTC, vgonkivs requested changes
Could you describe how the user should interact with the flag? In what units the timeout should be passed, bc duration represents time in nanoseconds.?

2024-08-14 14:38 UTC, sebasti810 commented
@vgonkivs The flag docstring prints the usage, e.g. 30s, 1m. This is because pflag has a DurationVar option, which handles this parsing underneath. 

And it's tested, this is the output you get when the timeline is exceeded
![image](https://github.com/user-attachments/assets/fa2692e9-15bb-4f50-b606-6a5939371541)

2024-08-23 21:49 UTC, jcstein commented
> 
@jcstein Did you test this PR already?

@renaynay just saw this, no I haven't tested it yet

2024-09-05 13:43 UTC, Wondertan requested changes
Hey @sebasti810! 

Thank you for the contribution

2024-09-05 13:43 UTC, Wondertan commented on cmd/rpc.go
> +	client, err := rpc.NewClient(cmd.Context(), requestURL, authTokenFlag, opts...)
There is a simpler way to achieve the same result.

We can pass through the timeout in the context. The timeout is respected by the RPC HTTP client performing the request, which avoids creating a new option for the client.

2024-10-02 13:39 UTC, renaynay submitted a review, later dismissed

2024-10-02 13:39 UTC, Wondertan submitted a review, later dismissed

2024-10-02 13:39 UTC, cristaloleg approved these changes

2024-10-02 14:28 UTC, cristaloleg commented on cmd/rpc.go
> +		ctx, _ := context.WithTimeout(cmd.Context(), timeoutFlag)
Can you add `//nolint:govet` here please?

2024-10-03 08:38 UTC, cristaloleg approved these changes

2024-10-03 08:38 UTC, walldiss approved these changes

2024-10-03 08:38 UTC, merged