initial POC for grpc tls
celestiaorg/celestia-node pull request #3917
Opened 2024-11-05 04:27 UTC by jhawk28

Initial concept for gRPC tls support

2024-11-05 04:52 UTC, a26nine commented
I was able to sync a light node with:
```
[Core]
  IP = "xxx.celestia-mainnet.quiknode.pro"
  RPCPort = "443"
  GRPCPort = "9090"
  EnableTLS = true
```
using this build.

2024-11-05 16:53 UTC, vgonkivs requested changes

2024-11-05 16:53 UTC, vgonkivs commented on state/core_access.go
> +		grpcOpts = append(grpcOpts, grpc.WithTransportCredentials(credentials.NewTLS(&tls.Config{})))
Without specifying valid certificates in the tls.Config object will not secure gRPC connection. By default, an empty tls.Config{} means that no certificate or private key is provided, which leads to an insecure setup.

Node already has TLS certificates handling logic [here](https://github.com/celestiaorg/celestia-node/blob/ace6840bb00b337c320c07be4dbe10e4d853271d/nodebuilder/p2p/tls.go#L24) for web socket, so you can reuse the certificate for the grpc connection.

2024-11-05 16:53 UTC, vgonkivs commented on nodebuilder/core/config.go
> +	EnableTLS bool
let's avoid growing the node's config. We have an env variable that signals that TLS should be enabled.

2024-11-05 18:28 UTC, jcstein commented
is it possible to set it up the same way that `rpc-mocha.pops.one` (mocha) works, for example? it uses the light node's default config and works by default (`celestia light start --p2p.network mocha --core.ip rpc-mocha.pops.one`)

2024-11-05 21:35 UTC, jhawk28 commented on state/core_access.go
> +		grpcOpts = append(grpcOpts, grpc.WithTransportCredentials(credentials.NewTLS(&tls.Config{})))
This was a proof of concept to get the Light node working against a Quicknode celestia endpoint. QN doesn't support client certs. gRPC auth for a QN endpoint occurs over the `x-token` header

2024-11-06 10:50 UTC, vgonkivs commented on state/core_access.go
> +		grpcOpts = append(grpcOpts, grpc.WithTransportCredentials(credentials.NewTLS(&tls.Config{})))
One more point here is the solution is not generic. You may not support the certificates but if someone does, the connection won't be established. Also, it is recommended to manually specify the MinTLSVersion(linter confirmed it)

2024-11-20 14:23 UTC, vgonkivs commented
closed in favor of #3954

2024-11-20 14:23 UTC, closed without merging