feat(shwap): implement GetRow
celestiaorg/celestia-node pull request #4002
Opened 2024-12-11 23:39 UTC by vgonkivs

2024-12-12 05:37 UTC, Wondertan reviewed
Generally LGTM

2024-12-12 05:37 UTC, Wondertan commented on share/shwap/getter.go
> +	// GetRow gets all shares from the specified row.
```suggestion
	// GetRow gets Row by its index committed to the given extended header.
```

2024-12-12 05:37 UTC, Wondertan commented on share/shwap/p2p/bitswap/getter.go
> +	defer span.End()
uber nit: new line

2024-12-12 05:37 UTC, Wondertan commented on share/shwap/row.go
> +		Side   RowSide          `json:"side"`
RowSide as 0,1,2 is not gonna be understandable for API consumers, like lumina. I wonder if we should make them readable strings instead in JSON.

2024-12-12 05:37 UTC, Wondertan commented on store/getter.go
> +		return shwap.Row{}, fmt.Errorf("get axis half from accessor:%w", err)
```suggestion
		return shwap.Row{}, fmt.Errorf("getting accessor from store: %w", err)
	}
	axisHalf, err := acc.AxisHalf(ctx, rsmt2d.Row, rowIdx)
	if err != nil {
		return shwap.Row{}, fmt.Errorf("getting axis half from accessor: %w", err)
```

2024-12-12 05:40 UTC, Wondertan commented on share/shwap/row_test.go
> +			require.Equal(t, row.side, decodedRow.side)
It should be its own test without calling `Shares` method as its gonna cache in #4005

2024-12-12 12:28 UTC, Wondertan commented on share/shwap/row.go
> +func (s RowSide) toString() string {
If we make it public String(), then loggers and stuff would recognise it as a stringer and print it instead, which is handy

2025-01-06 12:56 UTC, Wondertan commented on xtoken.json
> +{"x-token": "cdb1b3af1f4f7d841e948ed4a62cae4d4c1ee722"}
?

2025-01-06 12:56 UTC, Wondertan commented on share/shwap/row_test.go
> +		for _, side := range []RowSide{Left, Right} {
add Both

2025-01-06 13:58 UTC, cristaloleg commented on share/shwap/p2p/shrex/shrex_getter/shrex.go
> +	return shwap.Row{}, fmt.Errorf("getter/shrex: GetShare %w", shwap.ErrOperationNotSupported)
s/GetShare/GetRow

2025-01-06 14:07 UTC, Wondertan requested changes
Realized that this needs a Swamp test

2025-01-09 11:22 UTC, vgonkivs commented on xtoken.json
> +{"x-token": "cdb1b3af1f4f7d841e948ed4a62cae4d4c1ee722"}
artifact

2025-01-09 11:30 UTC, vgonkivs commented
> Realized that this needs a Swamp test

We don't have swamp tests for Share module. I'd open a subsequent PR with swamp tests to not bloat this one.

2025-01-09 12:05 UTC, Wondertan approved these changes

2025-01-09 13:30 UTC, cristaloleg approved these changes
SGTM

2025-01-09 15:14 UTC, merged