add network name to protocol ID
celestiaorg/celestia-node pull request #496
Opened 2022-03-05 21:47 UTC by toanngosy

This pull request would close #493.

2022-03-06 20:08 UTC, renaynay approved these changes
LGTM and thanks for the contribution @toanngosy !

@Wondertan is this the format you were thinking?

We also need to add a changelog entry for this.

2022-03-06 21:02 UTC, toanngosy commented
Thanks @renaynay ! I added the changelog into `CHANGELOG-PENDING.md`.

2022-03-07 09:54 UTC, renaynay approved these changes

2022-03-07 10:21 UTC, Wondertan requested changes
Thank you for tackling this.

2022-03-07 10:21 UTC, Wondertan commented on service/header/p2p_exchange.go
> +var exchangeProtocolID = protocol.ID(fmt.Sprintf("/header-ex-%s/v0.0.1", params.GetNetwork()))
I believe the format should be like `/header-ex/v0.0.01/network`. Sorry for not mentioning this in the issue

2022-03-08 01:46 UTC, toanngosy commented
@Wondertan it should work now 😄

2022-03-08 06:02 UTC, Wondertan commented
Pls look at the commit history, @toanngosy. There are multiple duplicates from the master. Seems like artifacts from the rebasr. Needs to be fixed

2022-03-08 07:12 UTC, toanngosy commented
sorry, I fixed it. It is now up to date with the main. @Wondertan

2022-03-08 07:15 UTC, Wondertan approved these changes
:shipit:

2022-03-08 08:27 UTC, renaynay approved these changes
Thank you so much for your contribution @toanngosy ❤️

2022-03-08 13:18 UTC, merged