node|cmd: Make `StateService` required on node for all node types
celestiaorg/celestia-node pull request #573
Opened 2022-03-30 17:17 UTC by renaynay

Make `StateService` required on `node`. As we only have the `CoreAccess` implementation of `StateAccessor` for now, all nodes will be required to pass a `--core.remote` endpoint on init/start or else construction will fail. Eventually when we implement `P2PAccess`, a core endpoint will be optional, but `StateService` will still be required.

2022-03-30 18:01 UTC, Wondertan requested changes
Let's extract the .girignore change into a separate PR which also includes change in makefile which make it build not in the root but into ‘build’ folder

2022-03-30 19:16 UTC, adlerjohn commented
Do you mean temporary build files, or the final binary? The final binary should probably be in `bin` rather than `build`.

2022-03-30 19:35 UTC, Wondertan commented
> Do you mean temporary build files, or the final binary? The final binary should probably be in `bin` rather than `build`.

@adlerjohn I assume that ‘make build’ is for temporary builds. We don't store final builds in the repo.

2022-03-31 11:17 UTC, liamsi approved these changes

2022-04-01 11:12 UTC, renaynay commented on cmd/celestia/cmd.go
> +func parseFlags(cmd *cobra.Command, args []string) error {
I mean the same way we have `baseComponents`, we can have `baseFlags` func parsing for base flags and then have the remainder custom to node type flags additionally?

2022-04-01 11:28 UTC, Wondertan requested changes

2022-04-01 11:28 UTC, Wondertan commented on cmd/celestia/full.go
> +		err = cmdnode.ParseTrustedHashFlags(cmd, env)
Full node also needs trusted peer thus we should allow it to be modified

2022-04-01 11:28 UTC, Wondertan commented on cmd/celestia/light.go
> +		err = cmdnode.ParseMiscFlags(cmd)
* Why order change?
* Same here about trusted peer. Why did you remove it?

2022-04-01 13:17 UTC, Wondertan approved these changes

2022-04-01 13:23 UTC, merged